version: '3.9'

services:
  db_cinexplorer:
    image: postgres:12
    container_name: db_cinexplorer
    environment:
      POSTGRES_DB: cinexplorer_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}